### ISSUE TITLE
Consider using ubuntu:cosmic

### ISSUE THREAD

**Issue by caiopo** [aBARICHELLO/godot-ci#1]
https://github.com/aBARICHELLO/godot-ci/blob/9feff5dc862e9ba6a2cad40aadff801649cf50bf/3.0.2/Dockerfile#L1

Xenial was released in 2016 and is kinda old. Cosmic is the lastest LTS, so it should be preferred if the rest of the tooling is compatible.

**Comment by aBARICHELLO** [comment]
Thanks @caiopo 🐈
