### ISSUE TITLE
Does jdk needs an update?

### ISSUE THREAD

**Issue by lazaromenezes** [abarichello/godot-ci#131]
I'm having trouble exporting for Android with 4.2.1 and it used to work with 4.1.3.

The build error I'm seeing is:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> error: invalid source release: 17
```

I see the Dockerfile is [installing JDK 11](https://github.com/abarichello/godot-ci/blob/b65c243be93bf3fb8f877dbd78d239be1de653a7/Dockerfile#L14C5-L14C28) although the docs for 4.2 [recomends using JDK 17](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#install-openjdk-17)

Is it really a necessary update? I'm happy to send a PR with the change if you believe this is the issue.

**Comment by Calinou** [comment]
- Fixed by https://github.com/abarichello/godot-ci/pull/132.
