### ISSUE TITLE
Git Worktree

### ISSUE THREAD

**Issue by abueide** [aBARICHELLO/godot-ci#25]
Hey, I'm getting this error when deploying to github pages.

/usr/bin/git worktree add --checkout github-pages-deploy-action-temp-deployment-folder origin/gh-pages
Preparing github-pages-deploy-action-temp-deployment-folder (identifier github-pages-deploy-action-temp-deployment-folder)
HEAD is now at 0b4b99a Deploying to gh-pages from  @ 59d1b5aa0c54698bf3976c1b5e2f8451916e17c8 🚀
/usr/bin/rsync -q -av --checksum --progress build/web/. github-pages-deploy-action-temp-deployment-folder --exclude .ssh --exclude .git --exclude .github
/usr/bin/git status --porcelain
 M index.pck
/usr/bin/git add --all .
/usr/bin/git checkout -b github-pages-deploy-action/yqcvcm0um
Switched to a new branch 'github-pages-deploy-action/yqcvcm0um'
M	index.pck
/usr/bin/git commit -m Deploying to gh-pages from  @ 9027b690b7b0935ebd6e953cfca476acb0f83308 🚀 --quiet
/usr/bin/git push --force ***github.com/ugdt/zelcrawler.git github-pages-deploy-action/yqcvcm0um:gh-pages
To https://github.com/ugdt/zelcrawler.git
   0b4b99a..8119bbc  github-pages-deploy-action/yqcvcm0um -> gh-pages
Changes committed to the gh-pages branch… 📦
/usr/bin/git checkout --progress --force 9027b690b7b0935ebd6e953cfca476acb0f83308
HEAD is now at 9027b69... Update github-pages
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
usage: git worktree add [<options>] <path> [<branch>]
   or: git worktree list [<options>]
   or: git worktree lock [<options>] <path>
   or: git worktree prune [<options>]
   or: git worktree unlock <path>

##[error]The process '/usr/bin/git' failed with exit code 129

**Comment by asheraryam** [comment]
I think maybe @OverloadedOrama has an idea about working with the github actions config.

Also see if https://github.com/aBARICHELLO/godot-ci/pull/22 has any useful info.

**Comment by OverloadedOrama** [comment]
I'm not sure, but it's possible the issue has to do with the fact that you're working in a private repository. #22 uses https://github.com/JamesIves/github-pages-deploy-action, so I suggest to take a look at the README on that repository to see if you need any more steps. You probably have to use a SHH Deploy Key.
