### ISSUE TITLE
Running example for github action

### ISSUE THREAD

**Issue by paul-asvb** [aBARICHELLO/godot-ci#35]
Hello,
im new to godot and trying to run my CI on github actions.
Can someone point me to an working example?

**Comment by asheraryam** [comment]
This is the latest config for github actions:
https://github.com/aBARICHELLO/godot-ci/blob/master/.github/workflows/godot-ci.yml

Make a folder on your repo called `.github`, then create a subfolder called `workflows`, then paste `godot-ci.yml` inside.

**Comment by paul-asvb** [comment]
Would you also do that in a real project? Have the godot project in a subdirectory?

**Comment by asheraryam** [comment]
That is up to you, there is not much difference (but you have to make sure your CI script points to the right project file).

**Comment by 2shady4u** [comment]
as an example, i used godot-ci with github actions for godot wild jam of a few months back: https://github.com/2shady4u/gwj24

**Comment by aBARICHELLO** [comment]
I think i'll create an example repository and include it in the readme, i'll also review the github action install process

**Comment by aBARICHELLO** [comment]
I have a second example repository to add: https://github.com/aBARICHELLO/game-off
I'm gonna be honest with you guys, I'm not a huge fan of GitHub Actions. I think GitLab CI is easier to setup. I don't know why but GitHub Actions is really hard to learn so I'm not the best candidate for improving this part of this project.
Closing this for now, let me know if you have other quesitons
