### ISSUE TITLE
Add GitHub Actions example

### ISSUE THREAD

**Issue by aBARICHELLO** [aBARICHELLO/godot-ci#4]
Add reference files to use this image with GitHub Actions

**Comment by josephbmanley** [comment]
I'm not sure if this would go here or within it's own issue, but I've been using your container for an actions pipeline and have encounter a bit of a weird conflict. So in your image, you install everything from your default users home directory.  GitHub actions
See: [https://help.github.com/en/articles/virtual-environments-for-github-actions](https://help.github.com/en/articles/virtual-environments-for-github-actions)

I got it to a successful build after repeating some of the steps done in your docker file:
```
    - name: Setup environment
      run: |
        wget https://downloads.tuxfamily.org/godotengine/3.1.1/Godot_v3.1.1-stable_export_templates.tpz

        mkdir ~/.cache
        mkdir -p ~/.config/godot
        mkdir -p ~/.local/share/godot/templates/3.1.1.stable
        unzip Godot_v3.1.1-stable_export_templates.tpz
        mv templates/* ~/.local/share/godot/templates/3.1.1.stable
        rm -f Godot_v3.1.1-stable_export_templates.tpz
    - name: Export Project
      run: |
        # Export for Linux
        mkdir -p ./build/linux
        godot --export Linux/X11 ./build/linux/project-vine

        # Export for Windows
        mkdir -p ./build/windows
        godot --export "Windows Desktop" ./build/windows/project-vine.exe

        # Export for OSX
        mkdir -p ./builds/mac
        godot --export "Mac OSX" ./build/mac/project-vine
```

**Comment by aBARICHELLO** [comment]
Currently testing Github Actions on branch actions
