### ISSUE TITLE
Add deploy to Itch.io

### ISSUE THREAD

**Issue by xuv** [aBARICHELLO/godot-ci#5]
Hello @aBARICHELLO 

This is not an issue, but a feature request. I'm submitting this especially because your docker image is so popular among all the Godot docker images available. And for a good reason, it provides excellent documentation. Thanks a lot for that.

Since you already have all these excellent examples on how to deploy the HTML5 game to Git(hub|lab) Pages. Adding deployment to Itch.io would complete this set as it's one of the most popular platform for Windows, Linux and Mac indie games.

[Itch.io Butler](https://itch.io/docs/butler/) needs to be available in the docker image. [Here is some inspiration on how to add it](https://github.com/benjymous/docker-itch-butler) ;)

And the user would need to provide his/her own Itch.io API key.

Let me know what you think.

**Comment by aBARICHELLO** [comment]
Thanks for the feedback, I'll look into the butler documentation.
