### ISSUE TITLE
3.2.4rc3 temporary build

### ISSUE THREAD

**Issue by MintStudios** [abarichello/godot-ci#51]
I'm here because I have an M1 mac and I'd like to use this CI build. Could we have a build for the latest RC?

**Comment by 2shady4u** [comment]
@MintStudios 
I don't think it is in this repository's spirit to publish docker templates of (unfinished) Release Candidates.
This repository will be updated whenever Godot v3.3-stable gets a proper release.

In the meantime you can either:
- Make your own Docker build based off a fork of this repository.
- Use a Docker repo that I made myself for testing my GDNative web exports:
https://hub.docker.com/repository/docker/ponders/godot-ci

  This implements Godot v3.3-RC9 and can be used by simply changing the following line in your YML from:
  `image: barichello/godot-ci:3.2.3`
  to:
  `image: ponders/godot-ci:latest`

Again, I do recommend either making your own Docker repo or just waiting until 3.3 gets released.
But if you are unable to wait feel free to use the Docker build linked above.
(Do take into account that it will probably be deleted at some point, so use with care!)

**Comment by abarichello** [comment]
Like Piet said we don't maintain release candidates since they are short-lived, also not having a Mac makes this scenario difficult for me to test.
