### ISSUE TITLE
Android export fail : no valid Android SDK Path

### ISSUE THREAD

**Issue by clement-or** [abarichello/godot-ci#59]
```
ERROR: _fs_changed: Cannot export project with preset 'Android Debug' due to configuration errors:
A valid Android SDK path is required in Editor Settings.
```

This error appears when android debug export is setup using the demo ci stage. I don't know if I did something wrong or if it's a bug that needs to be fixed in the docker image.

Version: 3.3.2

**Comment by abarichello** [comment]
I'm not sure how to reproduce this error. Just tested the android APK output from the 3.3.3 version and it works perfectly.
https://gitlab.com/barichello/godot-ci/-/jobs/1517625863

**Comment by 2shady4u** [comment]
Not sure how it is working in your case.. I'll have to check for differences. 
But in my case I do get this error:
![image](https://user-images.githubusercontent.com/42484461/134122357-b22440ba-97b2-4d80-b505-68d32764ce20.png)

And it was working in older versions of Godot (before 3.3.2).
I'll try to figure what is going on here...

**Comment by 2shady4u** [comment]
@abarichello the job that you linked is running on Godot 3.2.3:
![image](https://user-images.githubusercontent.com/42484461/134122671-4e88ace9-37df-44de-9887-7f3526e92282.png)

That's why it is working in your case 😄

**Comment by abarichello** [comment]
Lol, you're right. I'll test your changes then

**Comment by 2shady4u** [comment]
@abarichello doing some testing myself
https://github.com/2shady4u/godot-ci/tree/fix-android-export

Will tell when it works :)

**Comment by maxim-sheronov** [comment]
Hi there.
That could be great to fix this bug 😃 
Also there is one more issue. Latest android-sdk does not include sdkmanager, so you need to add something like this before calling it:

```
RUN wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip \
    unzip commandlinetools-linux-6609375_latest.zip -d cmdline-tools \
    mv cmdline-tools $ANDROID_HOME/ \
    export PATH=$ANDROID_HOME/cmdline-tools/tools/bin:$PATH
```

**Comment by maxim-sheronov** [comment]
Hey, there is one more issue.
Latest android-sdk doesn't include sdkmanager, so I figured out it to work with something like that **before** calling sdkmanager:

```
ENV ANDROID_HOME="/usr/lib/android-sdk"
RUN wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
RUN unzip commandlinetools-linux-*_latest.zip -d cmdline-tools
RUN mv cmdline-tools $ANDROID_HOME/

ENV PATH="${ANDROID_HOME}/cmdline-tools/cmdline-tools/bin:${PATH}"
```

**Comment by asheraryam** [comment]
@maxim-sheronov PR is welcome if you want to contribute the fix!

**Comment by maxim-sheronov** [comment]
> @maxim-sheronov PR is welcome if you want to contribute the fix!

Well, I made it working in custom image, so I probably can prepare a PR to make it available for people.

**Comment by dozingpip** [comment]
I'm getting this error for the mono-3.4.2 image... Not sure if I should open it as a new issue or what?
Exact failure message:
```
ERROR: Cannot export project with preset "Android" due to configuration errors:
Debug keystore not configured in the Editor Settings nor in the preset.
A valid Android SDK path is required in Editor Settings.
   at: _fs_changed (editor/editor_node.cpp:778)
ERROR: Project export failed with error code 3 for preset "Android".
   at: _fs_changed (editor/editor_node.cpp:801)
```


I also tried adding
```
echo $ANDROID_HOME
cat ~/.config/godot/editor_settings-3.tres
```

to the script for the build but got back:
```
$ echo $ANDROID_HOME
$ cat ~/.config/godot/editor_settings-3.tres
cat: /root/.config/godot/editor_settings-3.tres: No such file or directory
```
and it failed directly after that on that run.


Header from my pipeline log:
```
Running with gitlab-runner 14.8.0~beta.44.g57df0d52 (57df0d52)
  on blue-2.shared.runners-manager.gitlab.com/default XxUrkriX
Preparing the "docker+machine" executor 01:03
Using Docker executor with image barichello/godot-ci:mono-3.4.2 ...
Pulling docker image barichello/godot-ci:mono-3.4.2 ...
Using docker image sha256:cb8b24f1fd1d17af2f76eb4bb73dcb5781bfe9be35abb1dba7e9514b8afde8c6 for barichello/godot-ci:mono-3.4.2 with digest barichello/godot-ci@sha256:5f41a0a9ba6ea1eeaa3454863d7e4e8c5d37eee70bea4136d4eabd130a2ed963 ...
```

**Comment by Calinou** [comment]
@dozingpip Exporting Mono projects for Android is not supported yet: https://github.com/abarichello/godot-ci/issues/50
