### ISSUE TITLE
Godot-ci update script

### ISSUE THREAD

**Issue by abarichello** [abarichello/godot-ci#65]
Since Docker Hub's [automated builds](https://docs.docker.com/docker-hub/builds/) are now locked behind a $60/year plan creating a script to check for new godot releases everyday would help keep this project up to date with minimal manual intervention.

Workflow:
1. Check for a new godot release everyday.
2. If a new release is available build the docker image with the GODOT_ENV variable updated.
3. Commit a new tag and create a new GitHub release in this repository.

**Comment by Razzlegames** [comment]
I was thinking... You could run a Github `action` on a schedule to accomplish this. 

https://jasonet.co/posts/scheduled-actions/

 The action workflow can publish the latest Docker image to `DockerHub`, using an access token you create through your `DockerHub` account. 

 I think it shouldn't cost anything (other than time), but I imagine there are limits.  I did this with `wercker` pipelines, fairly recently (not a fan of their config setup, as it's not *all* in code).
