### ISSUE TITLE
Target path appears to be invalid?

### ISSUE THREAD

**Issue by bend-n** [abarichello/godot-ci#86]
```
ERROR: Project export failed for preset "Linux". The target path "../build/linux/chess.x86_64" appears to be invalid.
   at: _fs_changed (editor/editor_node.cpp:801)
```
This is probably 'not our bug' but I don't [understand it.](https://github.com/bend-n/chess/runs/6828536920?check_suite_focus=true)

**Comment by Calinou** [comment]
The target path is relative to the project directory, **not** your CWD.

**Comment by bend-n** [comment]
Thanks, replacing `..` with `.` fixed it. Should have noticed 😅
