### ISSUE TITLE
`editor_settings-3.tres` not set by dockerfile?

### ISSUE THREAD

**Issue by bend-n** [abarichello/godot-ci#88]
[see here](https://github.com/bend-n/chess/runs/7243684498?check_suite_focus=true):
```
cat: /github/home/.config/godot/editor_settings-3.tres: No such file or directory
find: '/github/home/.config': No such file or directory
...
ERROR: Cannot export project with preset "Android" due to configuration errors:
Debug keystore not configured in the Editor Settings nor in the preset.
A valid Android SDK path is required in Editor Settings.
   at: _fs_changed (editor/editor_node.cpp:778)
ERROR: Project export failed with error code 3 for preset "Android".
   at: _fs_changed (editor/editor_node.cpp:801)
```

**Comment by bend-n** [comment]
I found the issue was that godot did see it, but couldnt parse it and therefore just reset it to default.

**Comment by Calinou** [comment]
> I found the issue was that godot did see it, but couldnt parse it and therefore just reset it to default.

If you can reproduce this on a local machine, please report this on the main Godot repository. Godot should be modified to print an error message if it discards the editor settings file for any reason.

**Comment by bend-n** [comment]
> > I found the issue was that godot did see it, but couldnt parse it and therefore just reset it to default.
> 
> If you can reproduce this on a local machine, please report this on the main Godot repository. Godot should be modified to print an error message if it discards the editor settings file for any reason.

It does; if you launch the editor. otherwise its completely silent, do you want me to make a minimum reproduction project for the cli exports?

**Comment by Calinou** [comment]
> It does; if you launch the editor. otherwise its completely silent, do you want me to make a minimum reproduction project for the cli exports?

Yes, please do :slightly_smiling_face:

**Comment by bend-n** [comment]
Okay

**Comment by bend-n** [comment]
Either way, the current dockerfile sets the editor_settings-3.tres, but it then gets reset, with no error i could find.

**Comment by bend-n** [comment]
By the way, the reason this was happening was because unknown keys were found in the `editor_settings-3.tres` file, and godot didnt like it, so it reset it.
